services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    restart: always
    ports:
      - '5555:5555' # Prisma Studio
      - '3000:8443' # Node.js API
    volumes:
      - ./:/usr/src/app
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=mydb
      - PGUSER=myuser
      - PGPASSWORD=mypassword

    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432' # PostgreSQL
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
