services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    restart: always
    ports:
      - '5555:5555'
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    environment:
      - PGHOST=${POSTGRES_HOST}
      - PGPORT=${POSTGRES_PORT}
      - PGDATABASE=${POSTGRES_DATABASE}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL = postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}?schema=public

    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
